using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

/*namespace ConsoleApp1.Loops
{
    internal class Hwexample
    {
         public int Digitaverage(int num)
         {

            int sum = 0;
            while(num > 0)
            {
                int r = num%10
                sum = sum + r
                num = num/10 
                int average =
            }
         }
    }*/

